### ISSUE TITLE
PriceVariantsPart breaks when you have a TextProductAttributeField with unrestricted values.

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#106]
## Reproduction steps:
- Create a new content type.
- Add parts `ProductPart` and `PriceVariantsPart`.
- Add two `TextProductAttributeField` fields:
  - Size: has predefined values (e.g. Small, Medium, Large) and "Restrict to predefined values" is checked.
  - Color: don't change anything, i.e. predefined values is empty "Restrict to predefined values" is unchecked. (I just named this color but could be anything else, a plausible scenario is a t-shirt shop where you can add a custom text on your order.)
- Create a new content item.
- Set SKU as you wish, you should see 3 price variant fields for Small, Medium and Large prices.

## Problems:
- The currency dropdown stays as `---` instead of `USD` as configured (note, this is not related to [the other issue](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/105), if I replace `PriceVariantsPart` with `PricePart` it initializes correctly)
- When I press Publish the values aren't saved.
  - When I try to add it to the cart anyway I get "Can't add product sample because it doesn't have a price."

before publish:
![image](https://user-images.githubusercontent.com/4007293/162629660-2c1811a3-28b9-4066-a349-f50e31733be4.png)
after publish:
![image](https://user-images.githubusercontent.com/4007293/162629673-01c27782-19ee-409f-a05b-d2232bd66087.png)

During publish I see this error in the console log:
```
fail: OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator[0]
      IContentPartDisplayDriver thrown from OrchardCore.Commerce.Drivers.PriceVariantsPartDisplayDriver by RuntimeBinderException
      Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'RemoveAll'
         at CallSite.Target(Closure , CallSite , Object )
         at OrchardCore.Commerce.Drivers.PriceVariantsPartDisplayDriver.UpdateAsync(PriceVariantsPart part, IUpdateModel updater, UpdatePartEditorContext context) in E:\aux_c\repositories\orchard-core\OrchardCore.Commerce\OrchardCore.Commerce\Drivers\PriceVarian
tsPartDisplayDriver.cs:line 49
         at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentPartDisplayDriver.UpdateEditorAsync(ContentPart contentPart, ContentTypePartDefinition typePartDefinition, Up
dateEditorContext context)
         at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c.<<UpdateEditorAsync>b__9_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3](IEnumerable`1 events, Func`5 dispatch, T1 arg1, T2 arg2, T3 arg3, ILogger logger)
```

## Notes

If I add predefined values and check the box for the other field it starts to work correctly. I think a solution would be to filter the product attributes the `PriceVariantsPart` handles, to only include those with "Restrict to predefined values".

**Comment by DemeSzabolcs** [comment]
> When I press Publish the values aren't saved.

I think they are technically saved, but when opening the product edit page, the display driver can't load them properly.

**Comment by Psichorex** [comment]
Yes it is already solved just no PR yet. Problem is if you take a look at your screenshot in those  dictionary populations the second key shouldn't refet to model.XY but part.XY because this way you don't set the stored value to the viewModel but you its own null value to it again.
