### ISSUE TITLE
revert Inferred parameters are not always recognized correctly (#485) first,  (OCC-288)

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore.Commerce#489]
### Describe the bug

A clear and concise description of what the problem is.

### To Reproduce

1. Go to builder.MapPost("api/shoppingcart/add-item",

4. See error, could not hit the api server
POST /api/shoppingcart/add-item HTTP/1.1
Host: localhost:62354
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

{"Token":"4aqdbe0zbwa54scsx0w34efknc","ShoppingCartId":"4aqdbe0zbwa54scsx0w34efknc","Line":{"Quantity":1,"ProductSku":"TESTDISCOUNTEDPRODUCT","Attributes":null}}HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8
Server: Microsoft-IIS/10.0
Content-Security-Policy: base-uri 'self'; default-src 'self'; frame-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; form-action 'self'; img-src 'self' data:; object-src 'none'; frame-ancestors 'self'
X-Powered-By: ASP.NET
Date: Fri, 30 Aug 2024 18:49:06 GMT

System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Http.HttpContext' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at lambda_method49(Closure, Object, HttpContext, Object)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.<>c.<<UseNosniffContentTypeOptionsHeader>b__1_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.<>c__DisplayClass0_0.<<UseContentSecurityPolicyHeader>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService, IAuthenticationService authenticationService, ISchemaFactory schemaService, IDocumentWriter documentWriter)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at OrchardCore.Liquid.ScriptsMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__0_1>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Content-Type: application/json; charset=utf-8
Host: localhost:62354
Transfer-Encoding: chunked
### Expected behavior
revert Inferred parameters are not always recognized correctly (#485) first, 

private static async Task<IResult> AddItemAsync(
     [FromBody] AddItemViewModel addItemVM,
    // [FromServices]
IAuthorizationService authorizationService,
    // [FromServices]
HttpContext httpContext,
    // [FromServices]
IShoppingCartService shoppingCartService,
   //  [FromServices]
IHtmlLocalizer<AddItemViewModel> htmlLocalizer
   )

### Screenshots
![屏幕截图 2024-08-30 145759](https://github.com/user-attachments/assets/bce7672a-7c73-46c0-a2fe-2fc7006fcbab)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-288)

**Comment by canadacubachina** [comment]
Seems it was overrided by another PR, so close it

**Comment by infofromca** [comment]
Seems it was overridden by another one, so close it
